### ISSUE TITLE
WorldGen

### ISSUE THREAD

**Issue by Sandrox1099** [JasonMcRay/TheNewPack#2]
Found a lot of trees Underground with some grass and flowers around them.
I think they shouldn't be down there.

**Comment by JasonMcRay** [comment]
Lowered chance of Lush Caves in ActuallyAdditions.cfg file. It will still happen, but they should be 5x more rarer (1 chunk in 100 chunks; instead of 1 chunk in 20). If it will still be too much... We will keep lowering it.
