### ISSUE TITLE
Mod suggestions Fluid Converters

### ISSUE THREAD

**Issue by KewaiiGamer** [JasonMcRay/TheNewPack#4]
One thing I always loved to do on minecraft was RFTools Dim with liquids ONLY however some liquids have no use at all. Perhaps we can make a use to those liquids and convert them to other liquids. Like convert liquified iron(?) to Lava and generate energy from lava. That would be awesome for a KS pack.

https://minecraft.curseforge.com/projects/fluidconverters

**Comment by KewaiiGamer** [comment]
IIRC the conversion rate is configurable so it is possible to balance the mod to our tastes!

**Comment by JasonMcRay** [comment]
Converting one liquid to another does not make sense. Yes it is going to be KS pack, but I want to keep some sense and little bit of realism to it.
